name: Run test suite
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '26.1'
          - '27.1'
          - '28.1'
          - '29.1'
          - '30.1'

    steps:
    - uses: actions/setup-python@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master

    - uses: actions/checkout@v2

    - name: Test
      run: |
        cask install
        cask exec ert-runner

    - name: Test after byte-compilation
      run: |
        cask build
        cask exec ert-runner
